spring.application.name=springbootdemoapp

#Use wildcard(*) to expose all endpoint
management.endpoints.web.exposure.include=*
#Can also exposed individual endpoints with a comma-delimited list
#management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

#Exclude individual endpoints with a comma-delimited list
#management.endpoints.web.exposure.exclude=health,info


info.app.name=Spring Boot Demo App
info.app.description=A SpringBoot app
info.app.version=0.0.1

#server.port=7070

#Srt context path of application
#server.servlet.context-path=/demo